Update requirements.txt
Updating this Flask==1.0 to Flask==2.0 will fix the error "ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/init.py)", which is occurring while running the image.